import type { Country } from "~/types";

export const COUNTRIES: Country[] = [
  // Europe
  {
    name: "Austria",
    code: "AT",
    flag: "🇦🇹",
    currency: "EUR",
    region: "Europe",
  },
  {
    name: "Belgium",
    code: "BE",
    flag: "🇧🇪",
    currency: "EUR",
    region: "Europe",
  },
  {
    name: "Croatia",
    code: "HR",
    flag: "🇭🇷",
    currency: "EUR",
    region: "Europe",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    flag: "🇨🇿",
    currency: "CZK",
    region: "Europe",
  },
  {
    name: "Denmark",
    code: "DK",
    flag: "🇩🇰",
    currency: "DKK",
    region: "Europe",
  },
  {
    name: "Finland",
    code: "FI",
    flag: "🇫🇮",
    currency: "EUR",
    region: "Europe",
  },
  { name: "France", code: "FR", flag: "🇫🇷", currency: "EUR", region: "Europe" },
  {
    name: "Germany",
    code: "DE",
    flag: "🇩🇪",
    currency: "EUR",
    region: "Europe",
  },
  { name: "Greece", code: "GR", flag: "🇬🇷", currency: "EUR", region: "Europe" },
  {
    name: "Hungary",
    code: "HU",
    flag: "🇭🇺",
    currency: "HUF",
    region: "Europe",
  },
  {
    name: "Ireland",
    code: "IE",
    flag: "🇮🇪",
    currency: "EUR",
    region: "Europe",
  },
  { name: "Italy", code: "IT", flag: "🇮🇹", currency: "EUR", region: "Europe" },
  {
    name: "Luxembourg",
    code: "LU",
    flag: "🇱🇺",
    currency: "EUR",
    region: "Europe",
  },
  {
    name: "Netherlands",
    code: "NL",
    flag: "🇳🇱",
    currency: "EUR",
    region: "Europe",
  },
  { name: "Norway", code: "NO", flag: "🇳🇴", currency: "NOK", region: "Europe" },
  { name: "Poland", code: "PL", flag: "🇵🇱", currency: "PLN", region: "Europe" },
  {
    name: "Portugal",
    code: "PT",
    flag: "🇵🇹",
    currency: "EUR",
    region: "Europe",
  },
  {
    name: "Romania",
    code: "RO",
    flag: "🇷🇴",
    currency: "RON",
    region: "Europe",
  },
  {
    name: "Slovakia",
    code: "SK",
    flag: "🇸🇰",
    currency: "EUR",
    region: "Europe",
  },
  {
    name: "Slovenia",
    code: "SI",
    flag: "🇸🇮",
    currency: "EUR",
    region: "Europe",
  },
  { name: "Spain", code: "ES", flag: "🇪🇸", currency: "EUR", region: "Europe" },
  { name: "Sweden", code: "SE", flag: "🇸🇪", currency: "SEK", region: "Europe" },
  {
    name: "Switzerland",
    code: "CH",
    flag: "🇨🇭",
    currency: "CHF",
    region: "Europe",
  },
  {
    name: "United Kingdom",
    code: "GB",
    flag: "🇬🇧",
    currency: "GBP",
    region: "Europe",
  },

  // Africa
  { name: "Egypt", code: "EG", flag: "🇪🇬", currency: "EGP", region: "Africa" },
  {
    name: "Ethiopia",
    code: "ET",
    flag: "🇪🇹",
    currency: "ETB",
    region: "Africa",
  },
  { name: "Ghana", code: "GH", flag: "🇬🇭", currency: "GHS", region: "Africa" },
  { name: "Kenya", code: "KE", flag: "🇰🇪", currency: "KES", region: "Africa" },
  {
    name: "Mauritius",
    code: "MU",
    flag: "🇲🇺",
    currency: "MUR",
    region: "Africa",
  },
  {
    name: "Morocco",
    code: "MA",
    flag: "🇲🇦",
    currency: "MAD",
    region: "Africa",
  },
  {
    name: "Nigeria",
    code: "NG",
    flag: "🇳🇬",
    currency: "NGN",
    region: "Africa",
  },
  { name: "Rwanda", code: "RW", flag: "🇷🇼", currency: "RWF", region: "Africa" },
  {
    name: "Senegal",
    code: "SN",
    flag: "🇸🇳",
    currency: "XOF",
    region: "Africa",
  },
  {
    name: "South Africa",
    code: "ZA",
    flag: "🇿🇦",
    currency: "ZAR",
    region: "Africa",
  },
  {
    name: "Tanzania",
    code: "TZ",
    flag: "🇹🇿",
    currency: "TZS",
    region: "Africa",
  },
  {
    name: "Tunisia",
    code: "TN",
    flag: "🇹🇳",
    currency: "TND",
    region: "Africa",
  },
  { name: "Uganda", code: "UG", flag: "🇺🇬", currency: "UGX", region: "Africa" },

  // Americas
  {
    name: "Argentina",
    code: "AR",
    flag: "🇦🇷",
    currency: "ARS",
    region: "Americas",
  },
  {
    name: "Belize",
    code: "BZ",
    flag: "🇧🇿",
    currency: "BZD",
    region: "Americas",
  },
  {
    name: "Brazil",
    code: "BR",
    flag: "🇧🇷",
    currency: "BRL",
    region: "Americas",
  },
  {
    name: "Canada",
    code: "CA",
    flag: "🇨🇦",
    currency: "CAD",
    region: "Americas",
  },
  {
    name: "Chile",
    code: "CL",
    flag: "🇨🇱",
    currency: "CLP",
    region: "Americas",
  },
  {
    name: "Colombia",
    code: "CO",
    flag: "🇨🇴",
    currency: "COP",
    region: "Americas",
  },
  {
    name: "Costa Rica",
    code: "CR",
    flag: "🇨🇷",
    currency: "CRC",
    region: "Americas",
  },
  {
    name: "Ecuador",
    code: "EC",
    flag: "🇪🇨",
    currency: "USD",
    region: "Americas",
  },
  {
    name: "Mexico",
    code: "MX",
    flag: "🇲🇽",
    currency: "MXN",
    region: "Americas",
  },
  {
    name: "Panama",
    code: "PA",
    flag: "🇵🇦",
    currency: "PAB",
    region: "Americas",
  },
  { name: "Peru", code: "PE", flag: "🇵🇪", currency: "PEN", region: "Americas" },
  {
    name: "United States",
    code: "US",
    flag: "🇺🇸",
    currency: "USD",
    region: "Americas",
  },
  {
    name: "Uruguay",
    code: "UY",
    flag: "🇺🇾",
    currency: "UYU",
    region: "Americas",
  },

  // Asia
  { name: "Bahrain", code: "BH", flag: "🇧🇭", currency: "BHD", region: "Asia" },
  { name: "Cambodia", code: "KH", flag: "🇰🇭", currency: "KHR", region: "Asia" },
  { name: "China", code: "CN", flag: "🇨🇳", currency: "CNY", region: "Asia" },
  { name: "Georgia", code: "GE", flag: "🇬🇪", currency: "GEL", region: "Asia" },
  {
    name: "Hong Kong",
    code: "HK",
    flag: "🇭🇰",
    currency: "HKD",
    region: "Asia",
  },
  { name: "India", code: "IN", flag: "🇮🇳", currency: "INR", region: "Asia" },
  {
    name: "Indonesia",
    code: "ID",
    flag: "🇮🇩",
    currency: "IDR",
    region: "Asia",
  },
  { name: "Israel", code: "IL", flag: "🇮🇱", currency: "ILS", region: "Asia" },
  { name: "Japan", code: "JP", flag: "🇯🇵", currency: "JPY", region: "Asia" },
  { name: "Jordan", code: "JO", flag: "🇯🇴", currency: "JOD", region: "Asia" },
  { name: "Malaysia", code: "MY", flag: "🇲🇾", currency: "MYR", region: "Asia" },
  { name: "Oman", code: "OM", flag: "🇴🇲", currency: "OMR", region: "Asia" },
  {
    name: "Philippines",
    code: "PH",
    flag: "🇵🇭",
    currency: "PHP",
    region: "Asia",
  },
  { name: "Qatar", code: "QA", flag: "🇶🇦", currency: "QAR", region: "Asia" },
  {
    name: "Saudi Arabia",
    code: "SA",
    flag: "🇸🇦",
    currency: "SAR",
    region: "Asia",
  },
  {
    name: "Singapore",
    code: "SG",
    flag: "🇸🇬",
    currency: "SGD",
    region: "Asia",
  },
  {
    name: "South Korea",
    code: "KR",
    flag: "🇰🇷",
    currency: "KRW",
    region: "Asia",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    flag: "🇱🇰",
    currency: "LKR",
    region: "Asia",
  },
  { name: "Taiwan", code: "TW", flag: "🇹🇼", currency: "TWD", region: "Asia" },
  { name: "Thailand", code: "TH", flag: "🇹🇭", currency: "THB", region: "Asia" },
  { name: "Turkey", code: "TR", flag: "🇹🇷", currency: "TRY", region: "Asia" },
  { name: "UAE", code: "AE", flag: "🇦🇪", currency: "AED", region: "Asia" },
  { name: "Vietnam", code: "VN", flag: "🇻🇳", currency: "VND", region: "Asia" },

  // Oceania
  {
    name: "Australia",
    code: "AU",
    flag: "🇦🇺",
    currency: "AUD",
    region: "Oceania",
  },
  { name: "Fiji", code: "FJ", flag: "🇫🇯", currency: "FJD", region: "Oceania" },
  {
    name: "New Zealand",
    code: "NZ",
    flag: "🇳🇿",
    currency: "NZD",
    region: "Oceania",
  },
];

export const getCountry = (code: string): Country | undefined =>
  COUNTRIES.find((c) => c.code === code);

const countriesByRegion = COUNTRIES.reduce<Record<string, Country[]>>(
  (acc, country) => {
    (acc[country.region] ??= []).push(country);
    return acc;
  },
  {},
);

export const COUNTRIES_GROUPED = Object.entries(countriesByRegion)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([region, countries]: [string, Country[]]) => ({
    label: region,
    items: [...countries]
      .sort((a, b) => a.name.localeCompare(b.name))
      .map((country) => ({
        label: `${country.flag} ${country.name}`,
        value: country.code,
      })),
  }));
